# Let dein manage itself
# Required
[[plugins]]
repo = '~/.config/nvim/dein/repos/github.com/Shougo/dein.vim'
local = 1

[[plugins]]
repo ='~/Documents/Programming/Vim/denite-fasd.nvim'
local = 1

##---------
## General dependencies
##---------
[[plugins]]
repo = 'hecal3/vim-leader-guide'

[[plugins]]
repo = 'equalsraf/neovim-gui-shim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

##---------
## Search and movement plugins
##---------
[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
let g:vimfiler_as_default_explorer = 1
nmap <silent> - :<C-u> exe 'VimFiler ' . expand('%:p:h')<CR>
'''

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'brooth/far.vim'

[[plugins]]
repo = 'tweekmonster/braceless.vim'

[[plugins]]
repo = 'derekwyatt/vim-fswitch'
on_ft = ['c', 'cpp']

##---------
## Scratch
##---------
[[plugins]]
repo = 'Shougo/junkfile.vim'

##---------
## Tag
##---------
[[plugins]]
repo = 'ludovicchabant/vim-gutentags'

##---------
## Testing
##---------
[[plugins]]
repo = 'janko-m/vim-test'
lazy = 1
on_cmd = ['TestFile', 'TestNearest', 'TestLast', 'TestVisit', 'TestSuite']

##---------
## Undo
##---------
[[plugins]]
repo = 'mbbill/undotree'

##---------
## Completion Tools
##---------
# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'ncm2/ncm2'

[[plugins]]
repo = 'ncm2/ncm2-ultisnips'

[[plugins]]
repo = 'ncm2/ncm2-path'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'ncm2/ncm2-neoinclude'

##---------
## Unite
##---------
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'neoclide/denite-extra'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neomru.vim'
##---------
## Snippets
##---------
[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'
##---------
## Error Checking
##---------
[[plugins]]
repo = 'w0rp/ale'

##---------
## Source formatting
##---------
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

##---------
## Git stuff
##---------
[[plugins]]
repo = 'mhinz/vim-signify'
hook_add = '''
let g:signify_vcs_list = [ 'git' ]
let g:signify_realtime = 1
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
lazy = 1
on_cmd = ['Gina']
hook_source='''
    " Execute :Gina commit with <C-^> on "gina-status" buffer
    call gina#custom#mapping#nmap(
          \ 'status', '<C-^>',
          \ ':<C-u>Gina commit<CR>',
          \ {'noremap': 1, 'silent': 1},
          \)

    " Execute :Gina status with <C-^> on "gina-commit" buffer
    call gina#custom#mapping#nmap(
          \ 'commit', '<C-^>',
          \ ':<C-u>Gina status<CR>',
          \ {'noremap': 1, 'silent': 1},
          \)
'''
##---------
## Project stuff
##---------
[[plugins]]
repo = 'dbakker/vim-projectroot'

[[plugins]]
repo = 'tpope/vim-projectionist'

##---------
## Build/Run Tools
##---------
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_add = '''
let g:asyncrun_open = 8
command! -bang -nargs=* -complete=file Make AsyncRun -program=make @ <args>
'''

[[plugins]]
repo = 'tpope/vim-eunuch'
##---------
## Status Line
##---------
[[plugins]]
repo = 'itchyny/lightline.vim'
if = '!exists("g:gui_oni")'

[[plugins]]
repo = 'maximbaz/lightline-ale'
if = '!exists("g:gui_oni")'

[[plugins]]
repo = 'albertomontesg/lightline-asyncrun'
if = '!exists("g:gui_oni")'

##---------
## Colors
##---------
[[plugins]]
repo = 'dracula/vim'
##---------
## Utilities
##---------
[[plugins]]
repo = 'KabbAmine/zeavim.vim'
if = "!has('macunix')"
hook_add = '''
let g:zv_disable_mapping = 1
'''

[[plugins]]
repo = 'rizzatti/dash.vim'
if = "has('macunix')"

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'jamessan/vim-gnupg'
hook_add = '''
let g:GPGUsePipes=1
'''

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'metakirby5/codi.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'

##---------
## Subregion
##---------
[[plugins]]
repo = 'chrisbra/NrrwRgn'
hook_add = '''
let g:nrrw_rgn_nomap_nr = 1
let g:nrrw_rgn_nomap_Nr = 1
'''
##---------
## Language Specific {{{
##---------
##--------
## C/C++
##--------
[[plugins]]
repo = 'bfrg/vim-cpp-modern'

[[plugins]]
repo = 'dbgx/lldb.nvim'

##--------
## Meson
##--------
# [[plugins]]
# repo = 'mesonbuild/meson'
# rtp = 'data/syntax-highlighting/vim'

[[plugins]]
repo = 'igankevich/mesonic'

##---------
## Notes
##---------
[[plugins]]
repo = 'neoclide/macnote.vim'
hook_add = '''
let g:vim_markdown_math = 1
let g:macnote_note_directory = expand('$HOME/Dropbox/sync/macnote')
'''

##---------
## Latex
##---------
[[plugins]]
repo = 'lervag/vimtex'

##---------
## Python
##---------
[[plugins]]
repo = 'tshirtman/vim-cython'
lazy = 1
on_ft = 'cython'

[[plugins]]
repo = 'numirias/semshi'

[[plugins]]
repo = 'szymonmaszke/vimpyter'

[[plugins]]
repo = 'gu-fan/riv.vim'

[[plugins]]
repo = 'ncm2/ncm2-rst-subscope'
##---------
## Haskell
##---------
[[plugins]]
repo = 'Twinside/vim-haskellConceal'

[[plugins]]
repo = 'eagletmt/neco-ghc'
lazy = 1
on_ft = 'haskell'

[[plugins]]
repo = 'travitch/hasksyn'
##---------
## Markdown
##---------
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'itspriddle/vim-marked'
##---------
## Julia
##---------
[[plugins]]
repo = 'JuliaLang/julia-vim'

##---------
## JS
##---------
[[plugins]]
repo = 'pangloss/vim-javascript'
##---------
## Clojure
##---------
[[plugins]]
repo = 'guns/vim-clojure-highlight'
on_ft = 'clojure'

[[plugins]]
repo = 'guns/vim-clojure-static'

[[plugins]]
repo = 'guns/vim-slamhound'
lazy = 1
on_ft = 'clojure'

[[plugins]]
repo = 'tpope/vim-fireplace'
lazy = 1
on_ft = 'clojure'

[[plugins]]
repo = 'tpope/vim-leiningen'
lazy = 1
on_ft = 'clojure'
##---------
## Ruby
##---------
[[plugins]]
repo = 'ngmy/vim-rubocop'
lazy = 1
on_ft = 'ruby'

##---------
## R
##---------
[[plugins]]
repo = 'jalvesaq/Nvim-R'

##---------
## Rust
##---------
[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'
##---------
## TOML
##---------
[[plugins]]
repo = 'cespare/vim-toml'
##---------
## Vimscript
##---------
[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'ncm2/ncm2-vim'

[[plugins]]
repo = 'thinca/vim-prettyprint'
lazy = 1
on_cmd = ['PrettyPrint', 'PrettyPrint!', 'PP', 'PP!']

[[plugins]]
repo = 'junegunn/vader.vim'
lazy = 1
on_ft = 'vader'
##---------
## }}}
##---------
