# Let dein manage itself
# Required
[[plugins]]
repo = '~/.config/nvim/dein/repos/github.com/Shougo/dein.vim'
local = 1

##---------
## General dependencies
##---------
[[plugins]]
repo = 'hecal3/vim-leader-guide'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'equalsraf/neovim-gui-shim'

##---------
## Search and movement plugins
##---------
[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tweekmonster/braceless.vim'

##---------
## Undo
##---------
[[plugins]]
repo = 'mbbill/undotree'

##---------
## Completion Tools
##---------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
##---------
## Unite
##---------
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'
##---------
## Snippets
##---------
[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'
##---------
## Error Checking
##---------
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'rhysd/vim-grammarous'
##---------
## Source formatting
##---------
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'sbdchd/neoformat'
##---------
## Git stuff
##---------
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'lambdalisue/gina.vim'
lazy = 1
on_cmd = ['Gina']
hook_source='''
    " Execute :Gina commit with <C-^> on "gina-status" buffer
    call gina#custom#mapping#nmap(
          \ 'status', '<C-^>',
          \ ':<C-u>Gina commit<CR>',
          \ {'noremap': 1, 'silent': 1},
          \)

    " Execute :Gina status with <C-^> on "gina-commit" buffer
    call gina#custom#mapping#nmap(
          \ 'commit', '<C-^>',
          \ ':<C-u>Gina status<CR>',
          \ {'noremap': 1, 'silent': 1},
          \)
'''
##---------
## Project stuff
##---------
[[plugins]]
repo = 'dbakker/vim-projectroot'

[[plugins]]
repo = 'derekwyatt/vim-fswitch'
##---------
## Build/Run Tools
##---------
[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-eunuch'
##---------
## Status Line
##---------
[[plugins]]
repo = 'rafi/vim-tinyline'
if = '!exists("g:gui_oni")'
##---------
## Colors
##---------
[[plugins]]
repo = 'dracula/vim'
##---------
## Utilities
##---------
[[plugins]]
repo = 'KabbAmine/zeavim.vim'
if = "!has('macunix')"

[[plugins]]
repo = 'rizzatti/dash.vim'
if = "has('macunix')"

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'jamessan/vim-gnupg'

[[plugins]]
repo = 'tpope/vim-abolish'

##---------
## Subregion
##---------
[[plugins]]
repo = 'chrisbra/NrrwRgn'
##---------
## Language Specific {{{
##---------
##--------
## Meson
##--------
[[plugins]]
repo = 'mesonbuild/meson'
rtp = 'syntax-highlighting/vim'

##---------
## Notes
##---------
[[plugins]]
repo = 'fmoralesc/vim-pad'

##---------
## Latex
##---------
[[plugins]]
repo = 'lervag/vimtex'
##---------
## Python
##---------
[[plugins]]
repo = 'davidhalter/jedi-vim'
lazy = 1
on_ft = 'python'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'tshirtman/vim-cython'
lazy = 1
on_ft = 'cython'

[[plugins]]
repo = 'ambv/black'
on_ft = 'python'

[[plugins]]
repo = 'gu-fan/riv.vim'
##---------
## Haskell
##---------
[[plugins]]
repo = 'Twinside/vim-haskellConceal'

[[plugins]]
repo = 'eagletmt/neco-ghc'
lazy = 1
on_ft = 'haskell'

[[plugins]]
repo = 'travitch/hasksyn'
##---------
## Mathematica
##---------
[[plugins]]
repo = 'rsmenon/vim-mathematica'
##---------
## Markdown
##---------
[[plugins]]
repo = 'plasticboy/vim-markdown'
##---------
## Julia
##---------
[[plugins]]
repo = 'JuliaLang/julia-vim'

[[plugins]]
repo = 'JuliaEditorSupport/deoplete-julia'
lazy = 1

##---------
## JS
##---------
[[plugins]]
repo = 'pangloss/vim-javascript'
##---------
## Clojure
##---------
[[plugins]]
repo = 'guns/vim-clojure-highlight'
on_ft = 'clojure'

[[plugins]]
repo = 'guns/vim-clojure-static'

[[plugins]]
repo = 'guns/vim-slamhound'
lazy = 1
on_ft = 'clojure'

[[plugins]]
repo = 'tpope/vim-fireplace'
lazy = 1
on_ft = 'clojure'

[[plugins]]
repo = 'tpope/vim-leiningen'
lazy = 1
on_ft = 'clojure'
##---------
## Ruby
##---------
[[plugins]]
repo = 'ngmy/vim-rubocop'
lazy = 1
on_ft = 'ruby'
##---------
## R
##---------
[[plugins]]
repo = 'jalvesaq/Nvim-R'
##---------
## Rust
##---------
[[plugins]]
repo = 'rust-lang/rust.vim'
[[plugins]]
repo = 'racer-rust/vim-racer'
##---------
## TOML
##---------
[[plugins]]
repo = 'cespare/vim-toml'
##---------
## Vimscript
##---------
[[plugins]]
repo = 'thinca/vim-prettyprint'
lazy = 1
on_cmd = ['PrettyPrint', 'PrettyPrint!', 'PP', 'PP!']

[[plugins]]
repo = 'junegunn/vader.vim'
lazy = 1
on_ft = 'vader'
##---------
## }}}
##---------
