# Let dein manage itself
# Required
[[plugins]]
repo = '~/.config/nvim/dein/repos/github.com/Shougo/dein.vim'
local = 1

##---------
## General dependencies
##---------
[[plugins]]
repo = 'hecal3/vim-leader-guide'

[[plugins]]
repo = 'mhinz/vim-startify'

##---------
## Search and movement plugins
##---------
[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tweekmonster/braceless.vim'

##---------
## Undo
##---------
[[plugins]]
repo = 'mbbill/undotree'

##---------
## Completion Tools
##---------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
##---------
## Unite
##---------
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'
##---------
## Snippets
##---------
[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'
##---------
## Error Checking
##---------
[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'rhysd/vim-grammarous'
##---------
## Source formatting
##---------
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'
##---------
## Git stuff
##---------
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'lambdalisue/vim-gita'
lazy = 1
on_cmd = ['Gita']
##---------
## Project stuff
##---------
[[plugins]]
repo = 'dbakker/vim-projectroot'
##---------
## Build/Run Tools
##---------
[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-eunuch'
##---------
## Status Line
##---------
[[plugins]]
repo = 'rafi/vim-tinyline'
##---------
## Colors
##---------
[[plugins]]
repo = 'lifepillar/vim-solarized8'
##---------
## Utilities
##---------
[[plugins]]
repo = 'KabbAmine/zeavim.vim'
if = "!has('macunix')"

[[plugins]]
repo = 'rizzatti/dash.vim'
if = "has('macunix')"

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'tpope/vim-repeat'
##---------
## Subregion
##---------
[[plugins]]
repo = 'chrisbra/NrrwRgn'
##---------
## Language Specific {{{
##---------
##---------
## Org
##---------
[[plugins]]
repo = 'jceb/vim-orgmode'
lazy = 1
on_ft = 'org'
##---------
## Latex
##---------
[[plugins]]
repo = 'lervag/vimtex'
lazy = 1
on_ft = 'tex'
##---------
## Python
##---------
[[plugins]]
repo = 'davidhalter/jedi-vim'
lazy = 1
on_ft = 'python'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
lazy = 1
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
lazy = 1
on_ft = 'python'

[[plugins]]
repo = 'tshirtman/vim-cython'
lazy = 1
on_ft = 'cython'
##---------
## Haskell
##---------
[[plugins]]
repo = 'Twinside/vim-haskellConceal'
lazy = 1
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/neco-ghc'
lazy = 1
on_ft = 'haskell'

[[plugins]]
repo = 'travitch/hasksyn'
lazy = 1
on_ft = 'haskell'
##---------
## Mathematica
##---------
[[plugins]]
repo = 'rsmenon/vim-mathematica'
##---------
## HTML
##---------
[[plugins]]
repo = 'mattn/emmet-vim'
##---------
## Stylus
##---------
[[plugins]]
repo = 'wavded/vim-stylus'
##---------
## Markdown
##---------
[[plugins]]
repo = 'plasticboy/vim-markdown'
##---------
## Julia
##---------
[[plugins]]
repo = 'JuliaLang/julia-vim'

[[plugins]]
repo = 'JuliaEditorSupport/deoplete-julia'
lazy = 1
on_ft = 'julia'
##---------
## JS
##---------
[[plugins]]
repo = 'pangloss/vim-javascript'
##---------
## Clojure
##---------
[[plugins]]
repo = 'guns/vim-clojure-highlight'
lazy = 1
on_ft = 'clojure'

[[plugins]]
repo = 'guns/vim-clojure-static'
lazy = 1
on_ft = 'clojure'

[[plugins]]
repo = 'guns/vim-slamhound'
lazy = 1
on_ft = 'clojure'

[[plugins]]
repo = 'tpope/vim-fireplace'
lazy = 1
on_ft = 'clojure'

[[plugins]]
repo = 'tpope/vim-leiningen'
lazy = 1
on_ft = 'clojure'
##---------
## Ruby
##---------
[[plugins]]
repo = 'ngmy/vim-rubocop'
lazy = 1
on_ft = 'ruby'
##---------
## R
##---------
[[plugins]]
repo = 'jalvesaq/Nvim-R'
lazy = 1
on_ft = ['r', 'rnoweb', 'rmd']
##---------
## Rust
##---------
[[plugins]]
repo = 'rust-lang/rust.vim'
##---------
## Fish
##---------
[[plugins]]
repo = 'dag/vim-fish'
##---------
## Asymptote
##---------
[[plugins]]
repo = 'hura/vim-asymptote'
##---------
## TOML
##---------
[[plugins]]
repo = 'cespare/vim-toml'
##---------
## Vimscript
##---------
[[plugins]]
repo = 'thinca/vim-prettyprint'
lazy = 1
on_cmd = ['PrettyPrint', 'PrettyPrint!', 'PP', 'PP!']

[[plugins]]
repo = 'junegunn/vader.vim'
lazy = 1
on_ft = 'vader'
##---------
## }}}
##---------
