[ftplugin]
cpp = '''
setlocal expandtab shiftwidth=2 softtabstop=2
nmap <buffer> <LocalLeader>a :<C-u>A<cr>
'''

ruby = '''
setlocal softtabstop=2 shiftwidth=2 expandtab
'''

tex='''
setlocal nofoldenable
'''
